// IGTTYBTAP Google Sheets + reliable separate photo upload endpoint
// After copying into Apps Script: Deploy > Manage deployments > Edit > New version > Deploy.
const SPREADSHEET_ID='10p5umfZPhTH7yOm5JSgua-VziUSwskiqjjKtEwZxlbA';
const CONFIG={
 'On Campus':{meta:{place:1,average:2,power:3,hours:4},notes:{Ashlyn:5,Marc:6,Lena:7},start:8,metrics:['Seating','Noise','Comfortability','Bathroom','Cleanliness','Convenience']},
 'K-Town':{meta:{place:1,average:2,power:3,wifi:4,hours:5},notes:{Ashlyn:6,Marc:7,Lena:8},start:9,metrics:['Seating','Affordability','Price','Distance','Drinks Yumminess','Food Yumminess','Noise','Comfortability','Area','Bathroom']},
 'Fryft Zone':{meta:{place:1,average:2,power:3,wifi:4,hours:5},notes:{Ashlyn:7,Marc:8,Lena:9},start:10,metrics:['Seating','Affordability','Price','Distance','Drinks Yumminess','Food Yumminess','Noise','Comfortability','Area','Bathroom']}
};
const PERSON_OFFSET={Lena:0,Ashlyn:1,Marc:2};
function json_(o){return ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON)}
function doGet(){return json_({ok:true,service:'IGTTYBTAP ratings + separate photo uploads endpoint',version:5})}
function photoSheet_(ss){let sh=ss.getSheetByName('Photos');if(!sh){sh=ss.insertSheet('Photos');sh.appendRow(['Place','Area','Photo Type','Image URL','Drive File ID','Submitted By','Timestamp'])}return sh}
function photoFolder_(){const name='IGTTYBTAP Spot Photos';const it=DriveApp.getFoldersByName(name),folder=it.hasNext()?it.next():DriveApp.createFolder(name);try{folder.setSharing(DriveApp.Access.ANYONE_WITH_LINK,DriveApp.Permission.VIEW)}catch(e){}return folder}
function saveOnePhoto_(ss,p){const photo=p.photo;if(photo&&photo.url){if(!['cover','food','drinks'].includes(photo.type))throw new Error('Invalid photo type');if(!/^https:\/\/res\.cloudinary\.com\/k8af2qva\/image\/upload\//.test(String(photo.url)))throw new Error('Photo link must come from Cloudinary');photoSheet_(ss).appendRow([p.place,p.category,photo.type,photo.url,photo.publicId||'',p.person,new Date()]);SpreadsheetApp.flush();return{fileId:photo.publicId||'',url:photo.url}}if(!photo||!photo.data||!['cover','food','drinks'].includes(photo.type))throw new Error('Invalid photo payload');const m=String(photo.data).match(/^data:(image\/[a-zA-Z0-9.+-]+);base64,(.+)$/);if(!m)throw new Error('Invalid image data');const bytes=Utilities.base64Decode(m[2]);if(bytes.length>8*1024*1024)throw new Error('Photo is too large');const safe=String(p.place).replace(/[^a-z0-9_-]+/gi,'-')||'spot',folder=photoFolder_(),blob=Utilities.newBlob(bytes,m[1],safe+'-'+photo.type+'-'+Date.now()+'.jpg'),file=folder.createFile(blob);try{file.setSharing(DriveApp.Access.ANYONE_WITH_LINK,DriveApp.Permission.VIEW)}catch(e){}const url='https://drive.google.com/thumbnail?id='+file.getId()+'&sz=w1600';photoSheet_(ss).appendRow([p.place,p.category,photo.type,url,file.getId(),p.person,new Date()]);SpreadsheetApp.flush();return{fileId:file.getId(),url}}
function saveRating_(ss,p){const cfg=CONFIG[p.category];if(!cfg)throw new Error('Invalid category');if(!(p.person in PERSON_OFFSET))throw new Error('Invalid rater');if(!p.place)throw new Error('Place is required');const sheet=ss.getSheetByName(p.category);if(!sheet)throw new Error('Sheet not found');const last=Math.max(sheet.getLastRow(),1),places=last>1?sheet.getRange(2,1,last-1,1).getDisplayValues().flat():[],needle=String(p.place).trim().toLowerCase();let row=places.findIndex(x=>String(x).trim().toLowerCase()===needle);row=row<0?-1:row+2;if(p.mode==='existing'){if(row<0)throw new Error('That place is not in this category');if(cfg.meta.wifi&&p.wifi&&String(p.wifi).toUpperCase()!=='N/A')sheet.getRange(row,cfg.meta.wifi).setValue(p.wifi)}else{if(row>0)throw new Error('That place already exists. Choose Current place instead.');row=last+1;sheet.getRange(row,cfg.meta.place).setValue(p.place);sheet.getRange(row,cfg.meta.power).setValue(p.power||'N/A');if(cfg.meta.wifi)sheet.getRange(row,cfg.meta.wifi).setValue(p.wifi||'N/A');sheet.getRange(row,cfg.meta.hours).setValue(p.hours||'N/A');for(let j=0;j<cfg.metrics.length;j++)for(let off=0;off<3;off++)sheet.getRange(row,cfg.start+j*3+off).setValue('N/A')}sheet.getRange(row,cfg.notes[p.person]).setValue(p.notes||'');const off=PERSON_OFFSET[p.person];cfg.metrics.forEach((metric,j)=>{let value=p.scores&&p.scores[metric]!=null?p.scores[metric]:'N/A';if(value!==''&&String(value).toUpperCase()!=='N/A'){value=Number(value);if(!Number.isFinite(value)||value<0||value>10)throw new Error('Invalid '+metric+' rating')}else value='N/A';sheet.getRange(row,cfg.start+j*3+off).setValue(value)});const values=sheet.getRange(row,cfg.start,1,cfg.metrics.length*3).getValues()[0].filter(v=>typeof v==='number'&&isFinite(v));sheet.getRange(row,cfg.meta.average).setValue(values.length?values.reduce((a,b)=>a+b,0)/values.length:'N/A');SpreadsheetApp.flush();return{row}}
function doPost(e){const lock=LockService.getScriptLock();try{lock.waitLock(20000);const p=JSON.parse((e.postData&&e.postData.contents)||'{}');if(!p.place)throw new Error('Place is required');if(!(p.person in PERSON_OFFSET))throw new Error('Invalid rater');if(!CONFIG[p.category])throw new Error('Invalid category');const ss=SpreadsheetApp.openById(SPREADSHEET_ID);if(p.action==='photo'){const saved=saveOnePhoto_(ss,p);return json_({ok:true,action:'photo',place:p.place,type:p.photo.type,fileId:saved.fileId,url:saved.url})}const result=saveRating_(ss,p);return json_({ok:true,action:'rating',row:result.row,place:p.place,category:p.category,person:p.person})}catch(err){console.error(err);return json_({ok:false,error:String(err&&err.message||err)})}finally{try{lock.releaseLock()}catch(e){}}}