const RATING_CATEGORIES={
 'On Campus':['Seating','Noise','Comfortability','Bathroom','Cleanliness','Convenience'],
 'K-Town':['Seating','Affordability','Price','Distance','Drinks Yumminess','Food Yumminess','Noise','Comfortability','Area','Bathroom'],
 'Fryft Zone':['Seating','Affordability','Price','Distance','Drinks Yumminess','Food Yumminess','Noise','Comfortability','Area','Bathroom']
};
const RATING_WRITE_ENDPOINT='https://script.google.com/macros/s/AKfycbzxQPGjGszstAoaFttCqr8mxce4_3bCiNpxWCdY2BbbRiDT6Qsx1jdXK1lS9aIx8DFaRA/exec';
const FORM_PERSON_INDEX={Lena:0,Ashlyn:1,Marc:2};
function formSpots(){return typeof spots!=='undefined'&&Array.isArray(spots)?spots:[]}
function currentSpot(){const category=document.querySelector('#ratingCategory')?.value,name=document.querySelector('#existingPlace')?.value;return formSpots().find(s=>s.area===category&&s.name===name)}
function buildRatingFields(prefill=true){const category=document.querySelector('#ratingCategory')?.value||'On Campus',person=document.querySelector('#ratingPerson')?.value||'Lena',target=document.querySelector('#reviewerRatings');if(!target)return;const s=document.querySelector('#ratingMode')?.value==='existing'?currentSpot():null,idx=FORM_PERSON_INDEX[person];target.innerHTML=`<section class="reviewer-form"><h3>${person}'s field report${s?` · ${esc(s.name)}`:''}</h3><div class="form-field full"><label>${person}'s notes</label><textarea name="notes" placeholder="What stood out? What should we know?">${prefill&&s?esc(s.notes?.[person]||''):''}</textarea></div><div class="rating-fields">${RATING_CATEGORIES[category].map(metric=>{const old=prefill&&s?s.ratings?.[metric]?.[idx]:null;return `<div class="category-rating"><label>${metric}</label><input class="rating-input" name="score-${metric}" type="number" min="0" max="10" step="0.25" placeholder="N/A" value="${Number.isFinite(old)?old:''}">${s?`<small>${Number.isFinite(old)?'CURRENT: '+old:'CURRENT: N/A'}</small>`:''}</div>`}).join('')}</div>${s?`<p class="form-note">Existing values shown above belong to ${person}. Change any score to overwrite it. Leaving a field blank submits N/A for that category.</p>`:''}</section>`}
function updatePlaces(){const category=document.querySelector('#ratingCategory')?.value,select=document.querySelector('#existingPlace');if(!select)return;const previous=select.value,names=formSpots().filter(s=>s.area===category).map(s=>s.name).sort((a,b)=>a.localeCompare(b));select.innerHTML='<option value="">Select a place…</option>'+names.map(n=>`<option value="${esc(n)}">${esc(n)}</option>`).join('');if(names.includes(previous))select.value=previous;buildRatingFields()}
function updateMode(){const existing=document.querySelector('#ratingMode').value==='existing';document.querySelector('#newPlaceField').classList.toggle('hidden',existing);document.querySelector('#existingPlaceField').classList.toggle('hidden',!existing);document.querySelectorAll('.new-place-meta').forEach(el=>el.classList.toggle('hidden',existing||el.id==='wifiField'&&document.querySelector('#ratingCategory').value==='On Campus'));if(existing)updatePlaces();else buildRatingFields(false)}
function payloadFrom(form){const fd=new FormData(form),category=fd.get('category'),person=fd.get('person'),mode=fd.get('mode'),scores={};RATING_CATEGORIES[category].forEach(metric=>{const raw=String(fd.get(`score-${metric}`)||'').trim();scores[metric]=raw===''?'N/A':raw});return{category,person,mode,place:String(mode==='existing'?fd.get('existingPlace'):fd.get('place')||'').trim(),power:String(fd.get('power')||'N/A').trim()||'N/A',wifi:category==='On Campus'?'N/A':String(fd.get('wifi')||'N/A').trim()||'N/A',hours:String(fd.get('hours')||'N/A').trim()||'N/A',notes:String(fd.get('notes')||'').trim(),scores}}
async function submitNewRating(e){e.preventDefault();const status=document.querySelector('#ratingFormStatus'),payload=payloadFrom(e.currentTarget);if(!payload.place){status.textContent=payload.mode==='existing'?'Select a current place first.':'Enter the new place name.';status.className='form-status error';return}for(const [metric,v] of Object.entries(payload.scores)){if(v!=='N/A'&&(Number(v)<0||Number(v)>10)){status.textContent=`${metric} must be between 0 and 10.`;status.className='form-status error';return}}status.textContent='Sending rating to the field guide…';status.className='form-status';try{const r=await fetch(RATING_WRITE_ENDPOINT,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(payload)}),data=await r.json();if(!data.ok)throw new Error(data.error||'Submission failed');status.innerHTML=`Saved! <b>${payload.person}'s rating for ${payload.place}</b> has been updated.`;status.className='form-status success';await (typeof loadData==='function'?loadData():Promise.resolve());updatePlaces()}catch(err){console.error(err);status.textContent='Could not save: '+err.message;status.className='form-status error'}}
document.addEventListener('DOMContentLoaded',()=>{const category=document.querySelector('#ratingCategory'),person=document.querySelector('#ratingPerson'),mode=document.querySelector('#ratingMode'),existing=document.querySelector('#existingPlace');category?.addEventListener('change',()=>{document.querySelector('#wifiField').classList.toggle('hidden',category.value==='On Campus'||mode.value==='existing');if(mode.value==='existing')updatePlaces();else buildRatingFields(false)});person?.addEventListener('change',()=>buildRatingFields());mode?.addEventListener('change',updateMode);existing?.addEventListener('change',()=>buildRatingFields());buildRatingFields(false);updateMode();document.querySelector('#newRatingForm')?.addEventListener('submit',submitNewRating);setTimeout(()=>{if(mode?.value==='existing')updatePlaces()},1200)});