const RATING_CATEGORIES={
 'On Campus':['Seating','Noise','Comfortability','Bathroom','Cleanliness','Convenience'],
 'K-Town':['Seating','Affordability','Price','Distance','Drinks Yumminess','Food Yumminess','Noise','Comfortability','Area','Bathroom'],
 'Fryft Zone':['Seating','Affordability','Price','Distance','Drinks Yumminess','Food Yumminess','Noise','Comfortability','Area','Bathroom']
};
const RATING_WRITE_ENDPOINT='https://script.google.com/macros/s/AKfycbzxQPGjGszstAoaFttCqr8mxce4_3bCiNpxWCdY2BbbRiDT6Qsx1jdXK1lS9aIx8DFaRA/exec';
const FORM_PERSON_INDEX={Lena:0,Ashlyn:1,Marc:2};
function formSpots(){return typeof spots!=='undefined'&&Array.isArray(spots)?spots:[]}
function currentSpot(){const category=document.querySelector('#ratingCategory')?.value,name=document.querySelector('#existingPlace')?.value;return formSpots().find(s=>s.area===category&&s.name===name)}
function buildRatingFields(prefill=true){const category=document.querySelector('#ratingCategory')?.value||'On Campus',person=document.querySelector('#ratingPerson')?.value||'Lena',target=document.querySelector('#reviewerRatings');if(!target)return;const s=document.querySelector('#ratingMode')?.value==='existing'?currentSpot():null,idx=FORM_PERSON_INDEX[person];target.innerHTML=`<section class="reviewer-form"><h3>${person}'s field report${s?` · ${esc(s.name)}`:''}</h3><div class="form-field full"><label>${person}'s notes</label><textarea name="notes" placeholder="What stood out? What should we know?">${prefill&&s?esc(s.notes?.[person]||''):''}</textarea></div><div class="rating-fields">${RATING_CATEGORIES[category].map(metric=>{const old=prefill&&s?s.ratings?.[metric]?.[idx]:null;return `<div class="category-rating"><label>${metric}</label><input class="rating-input" name="score-${metric}" type="number" min="0" max="10" step="0.25" placeholder="N/A" value="${Number.isFinite(old)?old:''}">${s?`<small>${Number.isFinite(old)?'CURRENT: '+old:'CURRENT: N/A'}</small>`:''}</div>`}).join('')}</div></section>`}
function updatePlaces(){const category=document.querySelector('#ratingCategory')?.value,select=document.querySelector('#existingPlace');if(!select)return;const previous=select.value,names=formSpots().filter(s=>s.area===category).map(s=>s.name).sort((a,b)=>a.localeCompare(b));select.innerHTML='<option value="">Select a place…</option>'+names.map(n=>`<option value="${esc(n)}">${esc(n)}</option>`).join('');if(names.includes(previous))select.value=previous;buildRatingFields();syncWifiField()}
function syncWifiField(){const field=document.querySelector('#wifiField'),select=field?.querySelector('select[name=wifi]');if(!select)return;const existing=document.querySelector('#ratingMode')?.value==='existing',offCampus=document.querySelector('#ratingCategory')?.value!=='On Campus',keep=select.querySelector('option[value=""]'),label=document.querySelector('#wifiLabelText');field.classList.toggle('hidden',!offCampus);keep.hidden=keep.disabled=!existing;if(existing){const s=currentSpot(),v=s&&typeof wifiLabel==='function'?wifiLabel(s.wifi):'',known=['Good Wifi','Meh Wifi','Bad Wifi'].includes(v);select.value=known?v:'';label.textContent=s?`WiFi quality · current: ${known?v:'not set'}`:'WiFi quality'}else{if(!select.value)select.value='Good Wifi';label.textContent='WiFi quality'}}
function updateMode(){const existing=document.querySelector('#ratingMode').value==='existing';document.querySelector('#newPlaceField').classList.toggle('hidden',existing);document.querySelector('#existingPlaceField').classList.toggle('hidden',!existing);document.querySelectorAll('.new-place-meta').forEach(el=>el.classList.toggle('hidden',existing||el.id==='wifiField'&&document.querySelector('#ratingCategory').value==='On Campus'));syncWifiField();if(existing)updatePlaces();else buildRatingFields(false)}
function payloadFrom(form){const fd=new FormData(form),category=fd.get('category'),person=fd.get('person'),mode=fd.get('mode'),scores={};RATING_CATEGORIES[category].forEach(metric=>{const raw=String(fd.get(`score-${metric}`)||'').trim();scores[metric]=raw===''?'N/A':raw});return{action:'rating',category,person,mode,place:String(mode==='existing'?fd.get('existingPlace'):fd.get('place')||'').trim(),power:String(fd.get('power')||'N/A').trim()||'N/A',wifi:category==='On Campus'?'N/A':({'Good Wifi':'Yes','Meh Wifi':'Kinda','Bad Wifi':'No'}[String(fd.get('wifi')||'').trim()]||(mode==='existing'?'':'N/A')),hours:String(fd.get('hours')||'N/A').trim()||'N/A',notes:String(fd.get('notes')||'').trim(),scores}}
function compressPhoto(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=reject;reader.onload=()=>{const img=new Image();img.onerror=reject;img.onload=()=>{const max=1200,scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);resolve(c.toDataURL('image/jpeg',.7))};img.src=reader.result};reader.readAsDataURL(file)})}
function selectedPhotos(){const groups=[['coverPhotos','cover'],['foodPhotos','food'],['drinkPhotos','drinks']],out=[];for(const [id,type] of groups)for(const file of [...(document.getElementById(id)?.files||[])])out.push({type,file});return out}
async function sendPayload(payload){let res;try{res=await fetch(RATING_WRITE_ENDPOINT,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(payload)})}catch(e){const err=new Error('Could not reach the ratings sheet. Check your connection, and check the sheet before resubmitting in case it already saved.');err.userFacing=true;throw err}let data=null;try{data=await res.json()}catch(_){}if(!res.ok||!data){const err=new Error('The ratings sheet sent back an unexpected reply. Check the sheet before resubmitting.');err.userFacing=true;throw err}if(!data.ok){const err=new Error(data.error||'The ratings sheet rejected this submission.');err.userFacing=true;throw err}return data}
async function uploadPhotos(meta,photos,status){let ok=0,failed=[];for(let i=0;i<photos.length;i++){const item=photos[i];status.textContent=`Compressing photo ${i+1} of ${photos.length}…`;const data=await compressPhoto(item.file);status.textContent=`Uploading photo ${i+1} of ${photos.length}…`;try{await sendPayload({action:'photo',place:meta.place,category:meta.category,person:meta.person,photo:{type:item.type,name:item.file.name,data}});ok++}catch(e){console.error(e);failed.push(item.file.name)}await new Promise(r=>setTimeout(r,350))}return{ok,failed}}
function previewPhotos(){const target=document.querySelector('#photoPreview');if(!target)return;target.innerHTML='';['coverPhotos','foodPhotos','drinkPhotos'].forEach(id=>[...(document.getElementById(id)?.files||[])].forEach(file=>{const img=document.createElement('img');img.src=URL.createObjectURL(file);img.onload=()=>URL.revokeObjectURL(img.src);target.appendChild(img)}))}
async function submitNewRating(e){e.preventDefault();const form=e.currentTarget,status=document.querySelector('#ratingFormStatus'),payload=payloadFrom(form),photos=selectedPhotos();if(!payload.place){status.textContent=payload.mode==='existing'?'Select a current place first.':'Enter the new place name.';status.className='form-status error';return}for(const [metric,v] of Object.entries(payload.scores)){if(v!=='N/A'&&(Number(v)<0||Number(v)>10)){status.textContent=`${metric} must be between 0 and 10.`;status.className='form-status error';return}}const button=form.querySelector('.submit-rating');button.disabled=true;try{status.textContent='Saving rating…';status.className='form-status';await sendPayload(payload);await new Promise(r=>setTimeout(r,700));let uploaded=0,failedPhotos=[];if(photos.length)({ok:uploaded,failed:failedPhotos}=await uploadPhotos(payload,photos,status));status.innerHTML=`Submitted! <b>${esc(payload.person)}'s rating for ${esc(payload.place)}</b>${uploaded?` + ${uploaded} photo${uploaded===1?'':'s'}`:''}.${failedPhotos.length?` ${failedPhotos.length} photo${failedPhotos.length===1?'':'s'} didn't upload (${esc(failedPhotos.join(', '))}); try those again.`:''} Refreshing live data…`;status.className=failedPhotos.length?'form-status error':'form-status success';setTimeout(async()=>{try{if(typeof loadData==='function')await loadData();updatePlaces()}catch(_){}},3000)}catch(err){console.error(err);status.textContent=err&&err.userFacing?`Not saved: ${err.message}`:'Upload failed before all items were sent. Please try again.';status.className='form-status error'}finally{button.disabled=false}}
document.addEventListener('DOMContentLoaded',()=>{const category=document.querySelector('#ratingCategory'),person=document.querySelector('#ratingPerson'),mode=document.querySelector('#ratingMode'),existing=document.querySelector('#existingPlace');category?.addEventListener('change',()=>{if(mode.value==='existing')updatePlaces();else buildRatingFields(false);syncWifiField()});person?.addEventListener('change',()=>buildRatingFields());mode?.addEventListener('change',updateMode);existing?.addEventListener('change',()=>{buildRatingFields();syncWifiField()});['coverPhotos','foodPhotos','drinkPhotos'].forEach(id=>document.getElementById(id)?.addEventListener('change',previewPhotos));buildRatingFields(false);updateMode();document.querySelector('#newRatingForm')?.addEventListener('submit',submitNewRating);setTimeout(()=>{if(mode?.value==='existing')updatePlaces()},1200)});