const SHEET_ID='10p5umfZPhTH7yOm5JSgua-VziUSwskiqjjKtEwZxlbA';
const REVIEWERS=['Lena','Ashlyn','Marc']; const TABS=['On Campus','K-Town','Fryft Zone']; let spots=[],favorites=[],area='All';
const $=s=>document.querySelector(s), esc=(s='')=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function csvParse(text){let out=[],row=[],v='',q=false;for(let i=0;i<text.length;i++){let c=text[i];if(q){if(c==='"'&&text[i+1]==='"'){v+='"';i++}else if(c==='"')q=false;else v+=c}else if(c==='"')q=true;else if(c===','){row.push(v);v=''}else if(c==='\n'){row.push(v.replace(/\r$/,''));out.push(row);row=[];v=''}else v+=c}row.push(v.replace(/\r$/,''));if(row.some(x=>x!==''))out.push(row);return out}
const num=x=>{let n=parseFloat(String(x??'').replace(/[^0-9.-]/g,''));return Number.isFinite(n)?n:null};
async function getTab(tab){const url=`https://docs.google.com/spreadsheets/d/${SHEET_ID}/gviz/tq?tqx=out:csv&sheet=${encodeURIComponent(tab)}&_=${Date.now()}`;const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error(`${tab}: ${r.status}`);return csvParse(await r.text())}
function parseSpotTab(rows,tab){if(rows.length<2)return[];return rows.slice(1).filter(r=>r[0]?.trim()).map(r=>{let ratings={},notes={};if(tab==='On Campus'){notes={Lena:r[5]||'',Ashlyn:r[6]||'',Marc:r[7]||''};const cats=['Seating','Noise','Comfortability','Bathroom','Cleanliness'];cats.forEach((cat,j)=>ratings[cat]=[num(r[8+j*3]),num(r[9+j*3]),num(r[10+j*3])]);return{name:r[0].trim(),area:tab,overall:num(r[1]),power:r[2]||'—',wifi:'—',hours:r[3]||'—',notes,ratings}}else{notes={Lena:r[6]||'',Ashlyn:r[7]||'',Marc:r[8]||''};const cats=['Affordability','Price','Distance','Seating','Drinks Yumminess','Food Yumminess','Noise','Comfortability','Area','Bathroom'];cats.forEach((cat,j)=>ratings[cat]=[num(r[9+j*3]),num(r[10+j*3]),num(r[11+j*3])]);return{name:r[0].trim(),area:tab,overall:num(r[1]),power:r[2]||'—',wifi:r[3]||'—',hours:r[4]||'—',notes,ratings}}})}
function personalScore(s,idx){let vals=Object.values(s.ratings||{}).map(v=>v[idx]).filter(Number.isFinite);return vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:null}
function calcFavorites(){favorites=REVIEWERS.map((person,idx)=>{let ranked=spots.filter(s=>s.area!=='On Campus').map(s=>({spot:s.name,score:personalScore(s,idx)})).filter(x=>Number.isFinite(x.score)).sort((a,b)=>b.score-a.score);return{person,...(ranked[0]||{spot:'More ratings needed',score:null})}})}
function stickyNotes(s,compact=false){const notes=REVIEWERS.map((p,i)=>({p,text:s.notes?.[p]||'',i})).filter(n=>n.text.trim());if(!notes.length)return'';return `<div class="sticky-wrap ${compact?'sticky-compact':''}">${notes.map(n=>`<div class="sticky sticky-${n.i}"><b>${esc(n.p)}</b><p>${esc(n.text)}</p></div>`).join('')}</div>`}
async function loadData(){const status=$('#dataStatus'),dot=$('#statusDot');try{const tabs=await Promise.all(TABS.map(async t=>[t,await getTab(t)]));spots=tabs.flatMap(([t,r])=>parseSpotTab(r,t));if(!spots.length)throw new Error('No rows returned');calcFavorites();status.textContent='Live from SPOT RANKINGS · refreshes from Google Sheets';dot.classList.add('live')}catch(e){console.error(e);status.textContent='Could not load the public Sheet · check sharing/publishing settings'}render();renderFavorites();updateHero()}
function updateHero(){const top=[...spots].filter(s=>Number.isFinite(s.overall)).sort((a,b)=>b.overall-a.overall)[0];$('#heroTop').textContent=top?.name||'More soon';$('#heroScore').textContent=top?top.overall.toFixed(2):'—'}
function render(){let data=spots.filter(s=>(area==='All'||s.area===area)&&s.name.toLowerCase().includes($('#search').value.toLowerCase()));data.sort($('#sort').value==='name'?(a,b)=>a.name.localeCompare(b.name):(a,b)=>(b.overall??-1)-(a.overall??-1));$('#resultCount').textContent=`${data.length} spot${data.length===1?'':'s'} on the menu`;$('#cards').innerHTML=data.length?data.map((s,i)=>`<article class="spot-card ${Object.values(s.notes||{}).some(Boolean)?'has-notes':''}" data-name="${esc(s.name)}"><div class="rankline"><span class="rank">${s.overall!=null?'#'+(i+1):'UNRATED'} · ${esc(s.area)}</span><span class="score">${s.overall!=null?s.overall.toFixed(2):'—'}</span></div><h3>${esc(s.name)}</h3><div class="area">${s.area==='On Campus'?'University Park · USC':esc(s.area)+' · Los Angeles'}</div><div class="amenities"><span>⚡ ${esc(s.power)} power</span>${s.area!=='On Campus'?`<span>◉ ${esc(s.wifi)} WiFi</span>`:''}<span>◷ ${esc(s.hours)}</span></div>${stickyNotes(s,true)}<div class="view">OPEN THE FIELD NOTES →</div></article>`).join(''):'<div class="empty">Nothing on the menu matches that search.</div>';document.querySelectorAll('.spot-card').forEach(c=>c.onclick=()=>openSpot(c.dataset.name))}
function openSpot(name){const s=spots.find(x=>x.name===name);if(!s)return;const rows=Object.entries(s.ratings||{}).map(([k,v])=>`<tr><th>${esc(k)}</th><td>${v?.[0]??'—'}</td><td>${v?.[1]??'—'}</td><td>${v?.[2]??'—'}</td></tr>`).join('');$('#modalContent').innerHTML=`<p class="eyebrow">${esc(s.area)} · FIELD NOTES</p><h2>${esc(s.name)}</h2><div class="modal-score">${s.overall!=null?s.overall.toFixed(2):'Unrated'}</div><div class="amenities"><span>⚡ ${esc(s.power)} power</span>${s.area!=='On Campus'?`<span>◉ ${esc(s.wifi)} WiFi</span>`:''}<span>◷ ${esc(s.hours)}</span></div>${stickyNotes(s)}${rows?`<table class="rating-table"><thead><tr><th>Category</th><th>Lena</th><th>Ashlyn</th><th>Marc</th></tr></thead><tbody>${rows}</tbody></table>`:''}`;$('#modal').classList.remove('hidden')}
function renderFavorites(){$('#favoriteGrid').innerHTML=favorites.map(f=>`<article class="favorite-card"><p class="eyebrow">${esc(f.person).toUpperCase()}'S HOUSE ORDER</p><h3>${esc(f.spot)}</h3><p>Highest average from ${esc(f.person)}’s own café ratings across K-Town and the Fryft Zone.</p><div class="favorite-score">${f.score!=null?f.score.toFixed(2):'—'} <small>/ 10</small></div></article>`).join('')}
document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');area=b.dataset.area;render()});$('#search').oninput=render;$('#sort').onchange=render;$('#closeModal').onclick=()=>$('#modal').classList.add('hidden');$('#modal').onclick=e=>{if(e.target.id==='modal')e.currentTarget.classList.add('hidden')};document.querySelectorAll('.nav-link').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav-link').forEach(x=>x.classList.remove('active'));b.classList.add('active');const fav=b.dataset.view==='favorites';$('#exploreView').classList.toggle('hidden',fav);$('#exploreHero').classList.toggle('hidden',fav);$('#favoritesView').classList.toggle('hidden',!fav);document.querySelector('.marquee').classList.toggle('hidden',fav)});document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();$('#search').focus()}if(e.key==='Escape')$('#modal').classList.add('hidden')});loadData();