const SHEET_ID='10p5umfZPhTH7yOm5JSgua-VziUSwskiqjjKtEwZxlbA';
const REVIEWERS=['Lena','Ashlyn','Marc']; const TABS=['On Campus','K-Town','Fryft Zone']; let spots=[],favorites=[],area='All',spotPhotos={};
const $=s=>document.querySelector(s), esc=(s='')=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function csvParse(text){let out=[],row=[],v='',q=false;for(let i=0;i<text.length;i++){let c=text[i];if(q){if(c==='"'&&text[i+1]==='"'){v+='"';i++}else if(c==='"')q=false;else v+=c}else if(c==='"')q=true;else if(c===','){row.push(v);v=''}else if(c==='\n'){row.push(v.replace(/\r$/,''));out.push(row);row=[];v=''}else v+=c}row.push(v.replace(/\r$/,''));if(row.some(x=>x!==''))out.push(row);return out}
const num=x=>{const s=String(x??'').trim();if(!s||s.toUpperCase()==='N/A')return null;const n=Number(s);return Number.isFinite(n)?n:null};
const textNote=x=>{const s=String(x??'').trim();return s&&/[A-Za-z]/.test(s)&&s.toUpperCase()!=='N/A'?s:''};
const wifiLabel=w=>{const s=String(w??'').trim();if(/^(yes|good)\b/i.test(s))return'Good Wifi';if(/^(meh|ok|okay|kinda)\b/i.test(s))return'Meh Wifi';if(/^(no|bad)\b/i.test(s))return'Bad Wifi';return /wi-?fi/i.test(s)?s.replace(/wi-?fi/i,'Wifi'):`${s} Wifi`};
const spotSlug=name=>String(name||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/&/g,'and').replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'');
const photoPath=(s,file)=>`images/spots/${spotSlug(s.name)}/${file}`;
function photoList(s,type){return spotPhotos[`${s.area}|${s.name}`]?.[type]||[]}
function cycleImg(s,type,fallback,alt){const list=photoList(s,type),src=list[0];if(!src)return `<span hidden></span>`;return `<img class="${list.length>1?'cycle-photo':''}" data-photo-key="${esc(s.area+'|'+s.name)}" data-photo-type="${type}" src="${esc(src)}" alt="${esc(alt)}" loading="lazy" onerror="photoFailed(this)">`}
function photoFailed(img){const list=spotPhotos[img.dataset.photoKey]?.[img.dataset.photoType],bad=img.getAttribute('src');if(list){const i=list.indexOf(bad);if(i>=0)list.splice(i,1);if(list.length){img.dataset.photoIndex=0;if(list.length<2)img.classList.remove('cycle-photo');img.src=list[0];return}}img.style.display='none';if(img.nextElementSibling)img.nextElementSibling.style.display='grid'}
function coverPhoto(s,compact=false){return `<div class="spot-cover ${compact?'spot-cover-card':''}">${cycleImg(s,'cover',photoPath(s,'cover.jpg'),s.name+' cover photo')}<div class="spot-photo-placeholder" style="display:${photoList(s,'cover').length?'none':'grid'}"><span>PHOTO COMING SOON</span><small>submit one in New Rating +</small></div><span class="film-label">${compact?'COVER.JPG':'LOCATION_01.JPG'}</span></div>`}
function galleryPhotos(s){const types=[['cover','COVER'],['food','FOOD'],['drinks','DRINKS']];return `<section class="spot-gallery-section"><div class="gallery-heading"><p class="eyebrow">PHOTO ROLL // DCIM</p><span>submitted by the crew</span></div><div class="spot-gallery">${types.map(([type,label],i)=>{const fallback=type==='cover'?photoPath(s,'cover.jpg'):photoPath(s,`photo-${i}.jpg`);return `<figure class="gallery-shot"><div class="gallery-image">${cycleImg(s,type,fallback,s.name+' '+label.toLowerCase())}<div class="spot-photo-placeholder" style="display:${photoList(s,type).length?'none':'grid'}"><span>ADD ${label} PHOTO</span><small>New Rating +</small></div></div><figcaption>${label} // ${photoList(s,type).length||0} SUBMITTED</figcaption></figure>`}).join('')}</div></section>`}
let photoTimer=null;function startPhotoCycles(){if(photoTimer)return;photoTimer=setInterval(()=>{document.querySelectorAll('img.cycle-photo').forEach(img=>{if(Math.random()<.35)return;const list=spotPhotos[img.dataset.photoKey]?.[img.dataset.photoType]||[];if(list.length>1){const i=(Number(img.dataset.photoIndex||0)+1)%list.length;img.dataset.photoIndex=i;img.src=list[i]}})},4000)}
async function getTab(tab){const url=`https://docs.google.com/spreadsheets/d/${SHEET_ID}/gviz/tq?tqx=out:csv&sheet=${encodeURIComponent(tab)}&_=${Date.now()}`;const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error(`${tab}: ${r.status}`);return csvParse(await r.text())}
function photoDate(v){const s=String(v||'').trim();let m=s.match(/^(\d{4})-(\d{2})-(\d{2})/);if(m)return `${m[1]}-${m[2]}-${m[3]}`;m=s.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})/);if(m)return `${m[3]}-${m[1].padStart(2,'0')}-${m[2].padStart(2,'0')}`;m=s.match(/Date\((\d{4}),(\d{1,2}),(\d{1,2})/);if(m)return `${m[1]}-${String(+m[2]+1).padStart(2,'0')}-${m[3].padStart(2,'0')}`;return ''}
window.photoLog=[];
async function loadPhotos(){try{const rows=await getTab('Photos');spotPhotos={};window.photoLog=[];rows.slice(1).forEach(r=>{const place=String(r[0]||'').trim(),area=String(r[1]||'').trim(),type=String(r[2]||'').trim().toLowerCase(),url=String(r[3]||'').trim();if(!place||!url)return;window.photoLog.push({place,area,type,url,person:String(r[5]||'').trim(),date:photoDate(r[6]),sessionId:String(r[7]||'').trim()});if(!area||!['cover','food','drinks'].includes(type))return;const key=`${area}|${place}`;spotPhotos[key]??={cover:[],food:[],drinks:[]};spotPhotos[key][type].push(url)})}catch(e){console.info('No Photos tab yet; using repo photos.',e)}}
function triples(row,start,count){const out={};for(let j=0;j<count;j++)out[j]=[num(row[start+j*3]),num(row[start+j*3+1]),num(row[start+j*3+2])];return out}
function parseSpotTab(rows,tab){if(rows.length<2)return[];return rows.slice(1).filter(r=>String(r[0]||'').trim()).map(r=>{if(tab==='On Campus'){const names=['Seating','Noise','Comfortability','Bathroom','Cleanliness','Convenience'];const t=triples(r,7,names.length),ratings={};names.forEach((n,j)=>ratings[n]=t[j]);return{name:String(r[0]).trim(),area:tab,overall:num(r[1]),power:r[2]||'—',wifi:'—',hours:r[3]||'—',notes:{Ashlyn:textNote(r[4]),Marc:textNote(r[5]),Lena:textNote(r[6])},ratings}}if(tab==='Fryft Zone'){const names=['Seating','Affordability','Price','Distance','Drinks Yumminess','Food Yumminess','Noise','Comfortability','Area','Bathroom'];const t=triples(r,9,names.length),ratings={};names.forEach((n,j)=>ratings[n]=t[j]);return{name:String(r[0]).trim(),area:tab,overall:num(r[1]),power:r[2]||'—',wifi:r[3]||'—',hours:r[4]||'—',notes:{Ashlyn:textNote(r[6]),Marc:textNote(r[7]),Lena:textNote(r[8])},ratings}}if(tab==='K-Town'){const names=['Seating','Affordability','Price','Distance','Drinks Yumminess','Food Yumminess','Noise','Comfortability','Area','Bathroom'];const t=triples(r,8,names.length),ratings={};names.forEach((n,j)=>ratings[n]=t[j]);return{name:String(r[0]).trim(),area:tab,overall:num(r[1]),power:r[2]||'—',wifi:r[3]||'—',hours:r[4]||'—',notes:{Ashlyn:textNote(r[5]),Marc:textNote(r[6]),Lena:textNote(r[7])},ratings}}return null}).filter(Boolean)}
const SHEET_REVIEWER_INDEX={Lena:0,Ashlyn:1,Marc:2};
function personalScore(s,person){const idx=SHEET_REVIEWER_INDEX[person],vals=Object.values(s.ratings||{}).map(v=>v[idx]).filter(Number.isFinite);return vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:null}
function topPersonal(person,onCampus){return spots.filter(s=>onCampus?s.area==='On Campus':s.area!=='On Campus').map(s=>({spot:s,score:personalScore(s,person)})).filter(x=>Number.isFinite(x.score)).sort((a,b)=>b.score-a.score||a.spot.name.localeCompare(b.spot.name))[0]||null}
function leastPersonal(person){const rated=spots.map(s=>({spot:s,score:personalScore(s,person)})).filter(x=>Number.isFinite(x.score));if(rated.length<2)return null;return rated.sort((a,b)=>a.score-b.score||a.spot.name.localeCompare(b.spot.name))[0]}
function calcFavorites(){favorites=REVIEWERS.map(person=>({person,onCampus:topPersonal(person,true),offCampus:topPersonal(person,false),least:leastPersonal(person)}))}
const SPRITE_FALLBACK={Lena:'images/sprites/lena-v2.svg'};
function spriteMarkup(person){return `<span class="pixel-person sprite-${person.toLowerCase()}"><i class="pixel-hair"></i><i class="pixel-head"></i><i class="pixel-eye e1"></i><i class="pixel-eye e2"></i><i class="pixel-body"></i><i class="pixel-leg l1"></i><i class="pixel-leg l2"></i><i class="pixel-shoe s1"></i><i class="pixel-shoe s2"></i></span>`}
function initNPCs(){if(document.querySelector('.npc-world'))return;const world=document.createElement('div');world.className='npc-world';world.innerHTML=REVIEWERS.map((p,i)=>`<div class="pixel-avatar npc-${p.toLowerCase()}" data-person="${p}" style="left:${12+i*20}vw;top:${42+i*9}vh"><span class="npc-name">${p}</span>${spriteMarkup(p)}</div>`).join('');document.body.appendChild(world);world.querySelectorAll('.pixel-person').forEach(el=>{const person=el.closest('.pixel-avatar').dataset.person,fallback=SPRITE_FALLBACK[person],m=getComputedStyle(el).backgroundImage.match(/url\(["']?(.*?)["']?\)/);if(!fallback)return;if(!m){el.style.backgroundImage=`url('${fallback}')`;return}const test=new Image();test.onerror=()=>{el.style.backgroundImage=`url('${fallback}')`};test.src=m[1]});world.querySelectorAll('.pixel-avatar').forEach((npc,i)=>{const wander=()=>{const cards=[...document.querySelectorAll('.spot-card,.favorite-card,.postcard')].filter(x=>{const r=x.getBoundingClientRect();return r.width&&r.height&&r.bottom>70&&r.top<innerHeight-40});let x,y;if(cards.length&&Math.random()<.72){const r=cards[Math.floor(Math.random()*cards.length)].getBoundingClientRect();x=Math.max(8,Math.min(innerWidth-55,r.left+Math.random()*Math.max(30,r.width-35)));y=Math.max(75,Math.min(innerHeight-70,r.top+Math.random()*Math.max(30,r.height-45)))}else{x=15+Math.random()*(innerWidth-75);y=90+Math.random()*(innerHeight-170)}const old=parseFloat(npc.style.left)||0;npc.classList.toggle('facing-left',x<old);npc.classList.add('walking');npc.style.left=x+'px';npc.style.top=y+'px';if(Math.random()<.45){setTimeout(()=>npc.classList.add('jumping'),700+Math.random()*900);setTimeout(()=>npc.classList.remove('jumping'),1500+Math.random()*900)}setTimeout(()=>npc.classList.remove('walking'),2600);setTimeout(wander,3000+Math.random()*4200)};setTimeout(wander,700+i*900)})}
function stickyNotes(s,compact=false){const notes=REVIEWERS.map(p=>({p,text:textNote(s.notes?.[p])})).filter(n=>n.text);if(!notes.length)return'';return `<div class="sticky-wrap ${compact?'sticky-compact':''}">${notes.map((n,i)=>`<div class="sticky sticky-${i}"><b>${esc(n.p)}</b><p>${esc(n.text)}</p></div>`).join('')}</div>`}
async function loadData(){const status=$('#dataStatus'),dot=$('#statusDot');try{const tabs=await Promise.all(TABS.map(async t=>[t,await getTab(t)]));spots=tabs.flatMap(([t,r])=>parseSpotTab(r,t));if(!spots.length)throw new Error('No rows returned');await loadPhotos();calcFavorites();status.textContent='Live from SPOT RANKINGS · refreshes from Google Sheets';dot.classList.add('live')}catch(e){console.error(e);status.textContent='Could not load the public Sheet · check sharing/publishing settings'}render();renderFavorites();updateHero();startPhotoCycles();initNPCs();window.dispatchEvent(new Event('spots-loaded'))}
function updateHero(){const top=[...spots].filter(s=>Number.isFinite(s.overall)).sort((a,b)=>b.overall-a.overall)[0];$('#heroTop').textContent=top?.name||'More soon';$('#heroScore').textContent=top?top.overall.toFixed(2):'—'}
function reviewerValue(vals,person){const v=vals?.[SHEET_REVIEWER_INDEX[person]];return Number.isFinite(v)?v:'N/A'}
function render(){let data=spots.filter(s=>(area==='All'||s.area===area)&&s.name.toLowerCase().includes($('#search').value.toLowerCase()));const rankOf=new Map(),rated=data.filter(s=>s.overall!=null).sort((a,b)=>b.overall-a.overall);rated.forEach((s,i)=>rankOf.set(s,i&&s.overall===rated[i-1].overall?rankOf.get(rated[i-1]):i+1));data.sort($('#sort').value==='name'?(a,b)=>a.name.localeCompare(b.name):(a,b)=>(b.overall??-1)-(a.overall??-1));$('#resultCount').textContent=`${data.length} spot${data.length===1?'':'s'} on the menu`;$('#cards').innerHTML=data.length?data.map(s=>`<article class="spot-card photo-card ${Object.values(s.notes||{}).some(n=>textNote(n))?'has-notes':''}" data-name="${esc(s.name)}">${coverPhoto(s,true)}<div class="spot-card-body"><div class="rankline"><span class="rank">${s.overall!=null?'#'+rankOf.get(s):'UNRATED'} · ${esc(s.area)}</span><span class="score">${s.overall!=null?s.overall.toFixed(2):'—'}</span></div><h3>${esc(s.name)}</h3><div class="area">${s.area==='On Campus'?'University Park · USC':esc(s.area)+' · Los Angeles'}</div><div class="amenities"><span>⚡ ${esc(s.power)} power</span>${s.area!=='On Campus'?`<span>◉ ${esc(wifiLabel(s.wifi))}</span>`:''}<span>◷ ${esc(s.hours)}</span></div>${stickyNotes(s,true)}<div class="view">OPEN THE FIELD NOTES →</div></div></article>`).join(''):'<div class="empty">Nothing on the menu matches that search.</div>';document.querySelectorAll('.spot-card').forEach(c=>c.onclick=()=>openSpot(c.dataset.name));startPhotoCycles($('#cards'))}
function openSpot(name){const s=spots.find(x=>x.name===name);if(!s)return;const rows=Object.entries(s.ratings||{}).map(([k,v])=>`<tr><th>${esc(k)}</th><td>${reviewerValue(v,'Lena')}</td><td>${reviewerValue(v,'Ashlyn')}</td><td>${reviewerValue(v,'Marc')}</td></tr>`).join('');$('#modalContent').innerHTML=`<p class="eyebrow">${esc(s.area)} · FIELD NOTES</p><h2>${esc(s.name)}</h2>${coverPhoto(s)}<div class="modal-score">${s.overall!=null?s.overall.toFixed(2):'Unrated'}</div><div class="amenities"><span>⚡ ${esc(s.power)} power</span>${s.area!=='On Campus'?`<span>◉ ${esc(wifiLabel(s.wifi))}</span>`:''}<span>◷ ${esc(s.hours)}</span></div>${stickyNotes(s)}${rows?`<table class="rating-table"><thead><tr><th>Category</th><th>Lena</th><th>Ashlyn</th><th>Marc</th></tr></thead><tbody>${rows}</tbody></table>`:''}${galleryPhotos(s)}`;$('#modal').classList.remove('hidden');startPhotoCycles($('#modalContent'))}
function favPick(label,item,extra=''){if(!item)return `<div class="favorite-pick ${extra}"><p class="eyebrow">${label}</p><h3>More ratings needed</h3></div>`;return `<div class="favorite-pick ${extra}">${coverPhoto(item.spot,true)}<div style="padding:16px"><p class="eyebrow">${label}</p><h3>${esc(item.spot.name)}</h3><div class="area">${item.spot.area==='On Campus'?'USC Campus':esc(item.spot.area)}</div><div class="favorite-score">${item.score.toFixed(2)} <small>/ 10</small></div></div></div>`}
function renderFavorites(){$('#favoriteGrid').innerHTML=favorites.map(f=>`<article class="favorite-card"><div style="padding:22px"><p class="eyebrow">${esc(f.person).toUpperCase()}'S PICKS</p><h2 style="font-family:'Fraunces';color:var(--cardinal2);margin:8px 0 20px">${esc(f.person)}</h2>${favPick('FAVORITE ON CAMPUS',f.onCampus)}<div style="border-top:1px solid var(--line);margin:22px 0"></div>${favPick('FAVORITE OFF CAMPUS',f.offCampus)}<div style="border-top:1px dashed var(--line);margin:22px 0"></div>${favPick('LEAST FAVORITE',f.least,'least-pick')}</div></article>`).join('');startPhotoCycles($('#favoriteGrid'))}
document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');area=b.dataset.area;render()});$('#search').oninput=render;$('#sort').onchange=render;$('#closeModal').onclick=()=>$('#modal').classList.add('hidden');$('#modal').onclick=e=>{if(e.target.id==='modal')e.currentTarget.classList.add('hidden')};function showView(view){document.querySelectorAll('.nav-link').forEach(x=>x.classList.toggle('active',x.dataset.view===view));const explore=view==='explore';['#exploreView','#exploreHero','#raters','.marquee'].forEach(s=>document.querySelector(s)?.classList.toggle('hidden',!explore));$('#favoritesView').classList.toggle('hidden',view!=='favorites');$('#newRatingView')?.classList.toggle('hidden',view!=='new-rating');$('#studyView')?.classList.toggle('hidden',view!=='study');if(view==='study')window.StudyWrapped?.render();window.scrollTo({top:0,behavior:'instant'})}
document.querySelectorAll('.nav-link').forEach(b=>b.onclick=()=>showView(b.dataset.view));document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'&&!$('#exploreView').classList.contains('hidden')){e.preventDefault();$('#search').focus()}if(e.key==='Escape')$('#modal').classList.add('hidden')});loadData();