const SHEET_ID='10p5umfZPhTH7yOm5JSgua-VziUSwskiqjjKtEwZxlbA';
const REVIEWERS=['Lena','Ashlyn','Marc']; const TABS=['On Campus','K-Town','Fryft Zone']; let spots=[],favorites=[],area='All';
const $=s=>document.querySelector(s), esc=(s='')=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function csvParse(text){let out=[],row=[],v='',q=false;for(let i=0;i<text.length;i++){let c=text[i];if(q){if(c==='"'&&text[i+1]==='"'){v+='"';i++}else if(c==='"')q=false;else v+=c}else if(c==='"')q=true;else if(c===','){row.push(v);v=''}else if(c==='\n'){row.push(v.replace(/\r$/,''));out.push(row);row=[];v=''}else v+=c}row.push(v.replace(/\r$/,''));if(row.some(x=>x!==''))out.push(row);return out}
const num=x=>{const s=String(x??'').trim();if(!s)return null;const n=Number(s);return Number.isFinite(n)?n:null};
const textNote=x=>{const s=String(x??'').trim();return s&&/[A-Za-z]/.test(s)?s:''};
async function getTab(tab){const url=`https://docs.google.com/spreadsheets/d/${SHEET_ID}/gviz/tq?tqx=out:csv&sheet=${encodeURIComponent(tab)}&_=${Date.now()}`;const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error(`${tab}: ${r.status}`);return csvParse(await r.text())}
function triples(row,start,count){const out={};for(let j=0;j<count;j++)out[j]=[num(row[start+j*3]),num(row[start+j*3+1]),num(row[start+j*3+2])];return out}
function parseSpotTab(rows,tab){if(rows.length<2)return[];return rows.slice(1).filter(r=>String(r[0]||'').trim()).map(r=>{if(tab==='On Campus'){const names=['Seating','Noise','Comfortability','Bathroom','Cleanliness','Convenience'];const t=triples(r,7,names.length),ratings={};names.forEach((n,j)=>ratings[n]=t[j]);return{name:String(r[0]).trim(),area:tab,overall:num(r[1]),power:r[2]||'—',wifi:'—',hours:r[3]||'—',notes:{Ashlyn:textNote(r[4]),Marc:textNote(r[5]),Lena:textNote(r[6])},ratings}}if(tab==='Fryft Zone'){const names=['Seating','Affordability','Price','Distance','Drinks Yumminess','Food Yumminess','Noise','Comfortability','Area','Bathroom'];const t=triples(r,9,names.length),ratings={};names.forEach((n,j)=>ratings[n]=t[j]);return{name:String(r[0]).trim(),area:tab,overall:num(r[1]),power:r[2]||'—',wifi:r[3]||'—',hours:r[4]||'—',notes:{Ashlyn:textNote(r[6]),Marc:textNote(r[7]),Lena:textNote(r[8])},ratings}}if(tab==='K-Town'){const names=['Seating','Affordability','Price','Distance','Drinks Yumminess','Food Yumminess','Noise','Comfortability','Area','Bathroom'];const t=triples(r,8,names.length),ratings={};names.forEach((n,j)=>ratings[n]=t[j]);return{name:String(r[0]).trim(),area:tab,overall:num(r[1]),power:r[2]||'—',wifi:r[3]||'—',hours:r[4]||'—',notes:{Ashlyn:textNote(r[5]),Marc:textNote(r[6]),Lena:textNote(r[7])},ratings}}return null}).filter(Boolean)}
// Current rating triplets in the Sheet are Lena (green), Ashlyn (purple), Marc (blue).
const SHEET_REVIEWER_INDEX={Lena:0,Ashlyn:1,Marc:2};
function personalScore(s,person){const idx=SHEET_REVIEWER_INDEX[person];const vals=Object.values(s.ratings||{}).map(v=>v[idx]).filter(v=>Number.isFinite(v));return vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:null}
function topPick(person,predicate){const ranked=spots.filter(predicate).map(s=>({spot:s.name,area:s.area,score:personalScore(s,person)})).filter(x=>Number.isFinite(x.score)).sort((a,b)=>b.score-a.score||a.spot.localeCompare(b.spot));return ranked[0]||{spot:'More ratings needed',area:'',score:null}}
function calcFavorites(){favorites=REVIEWERS.map(person=>({person,onCampus:topPick(person,s=>s.area==='On Campus'),offCampus:topPick(person,s=>s.area!=='On Campus')}))}
function stickyNotes(s,compact=false){const notes=REVIEWERS.map((p,i)=>({p,text:textNote(s.notes?.[p]),i})).filter(n=>n.text);if(!notes.length)return'';return `<div class="sticky-wrap ${compact?'sticky-compact':''}">${notes.map(n=>`<div class="sticky sticky-${n.i}"><b>${esc(n.p)}</b><p>${esc(n.text)}</p></div>`).join('')}</div>`}
async function loadData(){const status=$('#dataStatus'),dot=$('#statusDot');try{const tabs=await Promise.all(TABS.map(async t=>[t,await getTab(t)]));spots=tabs.flatMap(([t,r])=>parseSpotTab(r,t));if(!spots.length)throw new Error('No rows returned');calcFavorites();status.textContent='Live from SPOT RANKINGS · refreshes from Google Sheets';dot.classList.add('live')}catch(e){console.error(e);status.textContent='Could not load the public Sheet · check sharing/publishing settings'}render();renderFavorites();updateHero()}
function updateHero(){const top=[...spots].filter(s=>Number.isFinite(s.overall)).sort((a,b)=>b.overall-a.overall)[0];$('#heroTop').textContent=top?.name||'More soon';$('#heroScore').textContent=top?top.overall.toFixed(2):'—'}
function reviewerValue(vals,person){return vals?.[SHEET_REVIEWER_INDEX[person]]??'—'}
function render(){let data=spots.filter(s=>(area==='All'||s.area===area)&&s.name.toLowerCase().includes($('#search').value.toLowerCase()));data.sort($('#sort').value==='name'?(a,b)=>a.name.localeCompare(b.name):(a,b)=>(b.overall??-1)-(a.overall??-1));$('#resultCount').textContent=`${data.length} spot${data.length===1?'':'s'} on the menu`;$('#cards').innerHTML=data.length?data.map((s,i)=>`<article class="spot-card ${Object.values(s.notes||{}).some(n=>textNote(n))?'has-notes':''}" data-name="${esc(s.name)}"><div class="rankline"><span class="rank">${s.overall!=null?'#'+(i+1):'UNRATED'} · ${esc(s.area)}</span><span class="score">${s.overall!=null?s.overall.toFixed(2):'—'}</span></div><h3>${esc(s.name)}</h3><div class="area">${s.area==='On Campus'?'University Park · USC':esc(s.area)+' · Los Angeles'}</div><div class="amenities"><span>⚡ ${esc(s.power)} power</span>${s.area!=='On Campus'?`<span>◉ ${esc(s.wifi)} WiFi</span>`:''}<span>◷ ${esc(s.hours)}</span></div>${stickyNotes(s,true)}<div class="view">OPEN THE FIELD NOTES →</div></article>`).join(''):'<div class="empty">Nothing on the menu matches that search.</div>';document.querySelectorAll('.spot-card').forEach(c=>c.onclick=()=>openSpot(c.dataset.name))}
function openSpot(name){const s=spots.find(x=>x.name===name);if(!s)return;const rows=Object.entries(s.ratings||{}).map(([k,v])=>`<tr><th>${esc(k)}</th><td>${reviewerValue(v,'Lena')}</td><td>${reviewerValue(v,'Ashlyn')}</td><td>${reviewerValue(v,'Marc')}</td></tr>`).join('');$('#modalContent').innerHTML=`<p class="eyebrow">${esc(s.area)} · FIELD NOTES</p><h2>${esc(s.name)}</h2><div class="modal-score">${s.overall!=null?s.overall.toFixed(2):'Unrated'}</div><div class="amenities"><span>⚡ ${esc(s.power)} power</span>${s.area!=='On Campus'?`<span>◉ ${esc(s.wifi)} WiFi</span>`:''}<span>◷ ${esc(s.hours)}</span></div>${stickyNotes(s)}${rows?`<table class="rating-table"><thead><tr><th>Category</th><th>Lena</th><th>Ashlyn</th><th>Marc</th></tr></thead><tbody>${rows}</tbody></table>`:''}`;$('#modal').classList.remove('hidden')}
function pickHTML(label,pick){return `<div class="favorite-pick"><p class="eyebrow">${label}</p><h3>${esc(pick.spot)}</h3>${pick.area?`<div class="area">${pick.area==='On Campus'?'USC Campus':esc(pick.area)}</div>`:''}<div class="favorite-score">${pick.score!=null?pick.score.toFixed(2):'—'} <small>/ 10</small></div></div>`}
function renderFavorites(){$('#favoriteGrid').innerHTML=favorites.map(f=>`<article class="favorite-card"><p class="eyebrow">${esc(f.person).toUpperCase()}'S PICKS</p><h2 style="font-family:'Fraunces';color:var(--cardinal2);margin:8px 0 24px">${esc(f.person)}</h2>${pickHTML('FAVORITE ON CAMPUS',f.onCampus)}<div style="border-top:1px solid var(--line);margin:24px 0"></div>${pickHTML('FAVORITE OFF CAMPUS',f.offCampus)}</article>`).join('')}
document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');area=b.dataset.area;render()});$('#search').oninput=render;$('#sort').onchange=render;$('#closeModal').onclick=()=>$('#modal').classList.add('hidden');$('#modal').onclick=e=>{if(e.target.id==='modal')e.currentTarget.classList.add('hidden')};document.querySelectorAll('.nav-link').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav-link').forEach(x=>x.classList.remove('active'));b.classList.add('active');const fav=b.dataset.view==='favorites';$('#exploreView').classList.toggle('hidden',fav);$('#exploreHero').classList.toggle('hidden',fav);$('#favoritesView').classList.toggle('hidden',!fav);document.querySelector('.marquee').classList.toggle('hidden',fav)});document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();$('#search').focus()}if(e.key==='Escape')$('#modal').classList.add('hidden')});loadData();